### PR TITLE
fix(docs): clarify tradeCode

### LINKED ISSUE #62: Add jsdoc for tradeCode, clarify that it is a server-side request
Add jsdoc for tradeCode, clarify that it is a server-side request.

This was asked twice, i.e https://github.com/mozilla/fxa-relier-client/issues/61

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #62

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson r?

File: client/token/api.js [hunk 1]
```diff
@@ -35,6 +35,9 @@ define([
      * Trade an OAuth code for a longer lived OAuth token. See
      * https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1token
      *
+     * This is most likely a server-side request. The trade code endpoint will not
```
Comment (shane-tomlinson) [inline client/token/api.js]: the linter is complaining about trailing spaces on all three of these lines.

**Comment by shane-tomlinson** [comment]
Other than the lint errors, r+. Merge when fixed.
